Fix/1185 mapping revisions
MRN-Code/coinstac pull request #1202
Opened 2022-02-14 18:31 UTC by kalitopix

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](../CONTRIBUTING.md)
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [x] Passes lint

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
closes #1185

* **What is the new behavior (if this is a feature change)?**
Updated mapping UI

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2022-02-14 20:07 UTC, rssk requested changes

2022-02-14 20:07 UTC, rssk commented on packages/coinstac-graphql-schema/src/queries.js
> -  fetchRunStatus: `
Why remove these?

2022-02-16 17:01 UTC, kalitopix commented on packages/coinstac-graphql-schema/src/queries.js
> -  fetchRunStatus: `
@rssk these two are duplicated.

<img width="338" alt="Screenshot 2022-02-16 at 12 00 50 PM" src="https://user-images.githubusercontent.com/48020962/154317037-ec68cd16-a57b-4aff-95ad-ac3f2cf41029.png">

2022-02-24 21:59 UTC, rssk commented on packages/coinstac-graphql-schema/src/queries.js
> -  fetchRunStatus: `
ah cool 👍

2022-03-29 21:19 UTC, rssk requested changes
needs to have the edit button visible on computations that have mappable fields that have already been mapped so they can be viewed etc

2023-10-12 01:34 UTC, rssk commented
outdated

2023-10-12 01:34 UTC, closed without merging