WIP Vault: upload artifacts to s3
MRN-Code/coinstac pull request #1352
Opened 2022-06-01 18:21 UTC by dylanmartin

* **Please check if the PR fulfills these requirements**
- [] The commit message follows our [guidelines](../CONTRIBUTING.md)
- [] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [] Tests for the changes have been added (for bug fixes / features)
- [] Passes e2e testing
- [] Passes lint
- [] Docs have been added / updated if necessary (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)
closes _issue #_

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-06-23 17:01 UTC, dylanmartin commented
@rssk we still need to talk about changing "headless" to "vault" throughout the codebase.

2022-06-24 19:39 UTC, dylanmartin commented
https://github.com/trendscenter/coinstac/issues/1351#issuecomment-1165878983

2022-06-27 19:07 UTC, dylanmartin commented on packages/coinstac-api-server/src/routes/cloudFiles.js
> +      payload: {
Try to upload and download a big file. 500mb

2022-06-27 20:03 UTC, rssk commented
Can you check if there are files to upload in the output directory?

2022-07-21 13:35 UTC, rssk requested changes

2022-07-21 13:35 UTC, rssk commented on packages/coinstac-client-core/src/index.js
> +
core has a logger instance that should be used for logs

2022-07-21 13:35 UTC, rssk commented on packages/coinstac-ui/app/main/index.js
> +            console.log('writeStream finished');
use the logger here too;)

2022-07-21 13:35 UTC, rssk commented on packages/coinstac-ui/app/render/components/results/result.jsx
> +                    this.setState({ downloading: false });
I'm guessing the top log is for debug, but the bottom should probably be wired to an error toast/notification

2022-07-27 17:26 UTC, rssk approved these changes

2022-07-27 17:26 UTC, merged