Feature/1348 add github links on computations ui
MRN-Code/coinstac pull request #1354
Opened 2022-06-02 22:29 UTC by kalitopix

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](../CONTRIBUTING.md)
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [] Tests for the changes have been added (for bug fixes / features)
- [] Passes e2e testing
- [] Passes lint
- [] Docs have been added / updated if necessary (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
closes #1348 

* **What is the new behavior (if this is a feature change)?**
Added GitHub links on computations UI

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2022-06-05 00:20 UTC, rssk requested changes
This is looking pretty good, lets change `testDataLink` to `testData`, and get rid of `projectLink` and make sure `repository` is the correct link type for be hotlinked

2022-06-09 22:18 UTC, rssk requested changes

2022-06-09 22:18 UTC, rssk commented on .eslintrc.js
> +    'no-console': 0,
why did you add this?

2022-06-09 22:36 UTC, kalitopix commented on .eslintrc.js
> +    'no-console': 0,
@rssk to avoid complaining `console.log(error)`

2022-06-11 21:06 UTC, merged