Refactor/consistent action dispatch
MRN-Code/coinstac pull request #236
Opened 2017-07-10 16:54 UTC by tkah

* **Problem:**
   1. Redux actions are not dispatched consistently. 
   1. Component database calls would be better served by already existing actions.
* **Solution:**
   1. Use shorthand pre-bound action creators as outlined [here](http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/).
   1. Call actions over separate database calls. (Really only one in `coinstac-ui/app/render/components/projects/form-project-controller.js`)
* **Tests:**
   1. `npm run test` in base directory
   1. `npm run test:e2e` in coinstac-ui package directory.

2017-07-24 17:09 UTC, swashcap requested changes

2017-07-24 17:09 UTC, swashcap commented on packages/coinstac-ui/app/render/components/user-account-controller.js
> -      <UserAccount logout={this.logout} {...this.props} />
Why change this property’s name?

2017-07-24 17:09 UTC, swashcap commented on packages/coinstac-ui/app/render/components/dashboard-consortia.js
> -              deleteConsortium={() => dispatch(deleteConsortium(id))}
In cases where you’re using multiple properties/functions from `this.props` it’s nice to destructure:

```js
const {
  deleteConsortium,
  joinConsortium,
  leaveConsortium,
} = this.props;

// ...
 <ConsortiumCard
  deleteConsortium={() => deleteConsortium(id)}
  joinConsortium={() => joinConsortium(id, username)}
  leaveConsortium={() => leaveConsortium(id, username)}
/>
```

A little nicer to read.

2017-07-24 17:09 UTC, swashcap commented on packages/coinstac-ui/app/render/components/consortium/consortium-controller.js
> +  addConsortiumComputationListener: PropTypes.func,
Holy additional prop types. 😲

2017-07-24 17:44 UTC, tkah commented on packages/coinstac-ui/app/render/components/consortium/consortium-controller.js
> +  addConsortiumComputationListener: PropTypes.func,
Yeah, using this manner of binding means more prop types unfortunately.

2017-07-24 17:45 UTC, tkah commented on packages/coinstac-ui/app/render/components/dashboard-consortia.js
> -              deleteConsortium={() => dispatch(deleteConsortium(id))}
👍

2017-07-24 17:53 UTC, tkah commented on packages/coinstac-ui/app/render/components/user-account-controller.js
> -      <UserAccount logout={this.logout} {...this.props} />
Adding a new prop called `logout` to take the place of the previously dispatched action `logout` meant that when we pass into `UserAccount` a function named `logout` referencing AccountController's local function in addition to using the spread operator to pass in all the props, including the new `logout` prop, we see issues. The UserAccount component would have two props named `logout`. So, I just renamed the local function.

2017-07-24 19:37 UTC, swashcap commented
@tkah Want to resolve the conflicts? Then I can test and merge.

2017-07-25 05:23 UTC, swashcap commented on packages/coinstac-ui/app/render/components/user-account-controller.js
> -      <UserAccount logout={this.logout} {...this.props} />
Looks like `UserAccount` only needs a `user` prop, but that makes total sense. We might want to pass more stuff from `UserAccount Controller` to `UserAccount` in the future.

2017-07-25 05:23 UTC, swashcap commented on packages/coinstac-ui/app/render/components/consortium/consortium-controller.js
> +  addConsortiumComputationListener: PropTypes.func,
Comes with the territory I guess :+1:

2017-07-25 05:34 UTC, swashcap approved these changes

2017-07-25 05:35 UTC, swashcap commented on packages/coinstac-ui/app/render/components/dashboard-home.jsx
> -    console.log('update');
Whoa, nice catch.

2017-07-25 05:36 UTC, merged