changed test to allow for existing consortia
MRN-Code/coinstac pull request #237
Opened 2017-07-10 17:23 UTC by tkah

* **Problem:**
   1. Tests fail when testing against system with already existing consortia.
* **Solution:**
    1. Specify which consortium is to be deleted/created.
* **Tests:**
   1. `npm run test:e2e` in coinstac-ui package directory.

2017-07-21 20:49 UTC, swashcap requested changes

2017-07-21 20:49 UTC, swashcap commented on packages/coinstac-ui/app/render/components/consortium-card.js
> +      <Button bsSize="small" bsStyle="danger" onClick={deleteConsortium} id={`delete-${label}`}>
A consortium’s `label` may have whitespace, which means selection by ID could break. Perhaps change to the consortium’s `id`?

2017-07-21 22:25 UTC, tkah commented on packages/coinstac-ui/app/render/components/consortium-card.js
> +      <Button bsSize="small" bsStyle="danger" onClick={deleteConsortium} id={`delete-${label}`}>
The reason I've added these `id` tags is to be able to grab them from WebdriverIO. In the e2e test, I don't have access to the `id` of a given consortium. I have the name I assign to it, though. Would you be alright with using a modified `label` with spaces replaced by dashes?

2017-07-21 23:00 UTC, swashcap commented on packages/coinstac-ui/app/render/components/consortium-card.js
> +      <Button bsSize="small" bsStyle="danger" onClick={deleteConsortium} id={`delete-${label}`}>
Ah, gotcha. That sounds like a good approach.

2017-07-24 16:38 UTC, swashcap approved these changes

2017-07-24 16:57 UTC, swashcap commented
@tkah This looks good. Could you fix the merge conflicts?

2017-07-24 17:50 UTC, swashcap commented
🎉 Works great!

2017-07-24 17:50 UTC, merged