Enhancement/Every process needs a log
MRN-Code/coinstac pull request #244
Opened 2017-07-13 22:18 UTC by tkah

* **Problem:**
   1. Main and render processes log their information to the same file, which can cause some confusion/inconvenience when debugging.
* **Solution:**
   1. Separate the `logger` into `mainLogger` and `renderLogger`, each pointing to different file.
* **Tests:**
   1. `npm run test` in base directory
   1. `npm run test:e2e` in coinstac-ui package directory.
   1. Check that two separate log files exist in the log directory.

2017-07-24 20:58 UTC, swashcap requested changes

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-client-core/src/index.js
> +    this.logger = opts.mainLogger || new Logger({ transports: [new Console()] });
We should keep this as `logger` so it’s more general. _coinstac-client-core_ should be environment-agnostic – unaware that it's running in a “main” Electron process.

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-ui/app/render/state/ducks/util.js
> +  app.renderLogger[level](msg);
Why expose  the logger as a two-argument function as opposed the default level-methods? Calls look cleaner:

```js
import { logUI as log } from '../state/ducks/util';
// ...
log('Imma message');
log.error('Oh noes!');
```

…versus:

```js
import { logUI as log from '../state/ducks/util';
// ...
log('info', 'Imma message');
log('error', 'Oh noes!');
```

This also means that one must look for two cases when attempting to track down log calls (`error`, for example: `log\.error` and `log\('error'`).

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-ui/app/main/utils/boot/configure-logger.js
>      if (cliOpts.loglevel) {
Not sure we ever use CLI-based log levels. Wonder if we need it.

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-ui/app/render/state/ducks/util.js
> +  app.renderLogger[level](msg);
Also, `logUI` is a bit redundant: we’re in the `render` directory, and these calls happen from modules containing user interface components. How does simply `log` sound?

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-ui/app/render/utils/boot/configure-logger.js
> -  app.logger = {
Can’t remember why we’re doing this. Seems pretty convoluted: a separate logger (wrapper?) for every method? This essentially decorates Winston methods. Wonder if there's another way around it.

2017-07-24 20:58 UTC, swashcap commented on packages/coinstac-ui/app/render/state/ducks/util.js
> +  app.renderLogger[level](msg);
_Also_ also, the render process’s logger still lives in the main process, and log calls are synchronous over RPC. Wonder if there's a better approach for this.

2017-09-20 21:33 UTC, rssk commented
What's up w/ this @tkah ?

2017-12-01 23:24 UTC, closed without merging