Add user permissions subscription
MRN-Code/coinstac pull request #602
Opened 2018-10-31 18:33 UTC by rochaeb

# Problem
referenced issue(s):

# Solution

# Testing

2018-11-02 17:42 UTC, rssk requested changes

2018-11-02 17:48 UTC, rochaeb commented on packages/coinstac-ui/app/render/components/dashboard/dashboard.jsx
> +      (!prevProps.currentUser || prevProps.currentUser.permissions !== this.props.currentUser.permissions)
Yes, I'm indeed only comparing references and this equality comparison probably has no utility... I was thinking of using Immutable to improve efficiency and making changes on the store only when necessary, but maybe we'll want this performance improvement only when we actually need it? What do you think?

2018-11-02 17:57 UTC, rochaeb commented on packages/coinstac-ui/app/render/state/graphql/props.js
> -        .then(({ data: { [name]: { permissions } } }) => {
What was happening here is that when a user created a consortium the api was processing the permission changes for that user and returning this. With this a permission change on the store was triggered. As we now have the subscription for this, I removed the this code.

I guess I could also remove the permissions "calculation" in the api mutation for adding/updating user roles.

2018-11-02 18:01 UTC, rochaeb commented on packages/coinstac-ui/app/render/components/dashboard/dashboard.jsx
> +      (!prevProps.currentUser || prevProps.currentUser.permissions !== this.props.currentUser.permissions)
This indeed is comparing references. As this is on the componentDidUpdate lifecycle method, this check prevents updating the store unnecessarily when the currentUser hasn't changed. We could improve this later (performance-wise) using Immutable for checking if the permissions did change when the user metadata subscription is triggered, but maybe we'll want to worry with this if we actually feel we need a performance improvement on this.

2018-11-02 18:12 UTC, rssk commented on packages/coinstac-ui/app/render/components/dashboard/dashboard.jsx
> +      (!prevProps.currentUser || prevProps.currentUser.permissions !== this.props.currentUser.permissions)
👍

2018-11-21 19:37 UTC, rssk approved these changes

2018-11-21 22:14 UTC, merged