Let user select the home directory for the app
MRN-Code/coinstac pull request #651
Opened 2019-02-21 21:01 UTC by rochaeb

# Problem
closes #646 

# Solution

# Testing

2019-03-06 20:55 UTC, rssk requested changes

2019-03-06 20:55 UTC, rssk commented on packages/coinstac-ui/app/render/state/ducks/auth.js
> +    caches.log('ER', err);
this intentional?

2019-03-07 18:10 UTC, rochaeb commented on packages/coinstac-ui/app/render/state/ducks/auth.js
> +    caches.log('ER', err);
no :p

2019-03-27 21:36 UTC, rssk approved these changes

2019-03-27 21:36 UTC, merged