Stop pipeline
MRN-Code/coinstac pull request #657
Opened 2019-03-26 16:42 UTC by abharathkr

# Problem
referenced feature(s): #643 

# Solution
Provided a "Stop Pipeline" button in consortia page for active pipeline
# Testing

2019-03-26 18:42 UTC, rssk requested changes

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-client-core/src/index.js
> +    return new Promise((res, rej) => {
Why create a new promise here? Also, this new promise doesnt resolve or reject anything, so you'll never actually get the async data to return right. `stopPipeline` should return a promise and thus you can just make this a one liner es6 arrow function

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-pipeline/src/controller.js
> +                console.log(controllerState);
;-)

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-pipeline/src/controller.js
> +                  err({message: 'Pipeline run is stopped by user'});
It's good practice to actually create an error when error'ing out, as often upstream code checks for object type. 
`err(new Error('Pipeline run is stopped by user'))`

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-pipeline/src/pipeline-manager.js
> +        this.activePipelines[runId].pipeline.pipelineSteps.forEach( step => {
Couple things here, the pipeline-manager here is directly mussing w/ pipeline objects, I try to do this only when absolutely necessary. Also, there is only ever one currently running pipeline `step` and so you would only need to ever stop that one. 
What needs to happen is that the call to stop the currently running step needs to happen from manager to a pipeline function, and that function needs to call the currently active step's controller, thus stopping the pipeline.

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-pipeline/src/pipeline-manager.js
> +        this.activePipelines[runId].pipeline.pipelineSteps.forEach( step => {
Also also, docbloc your functions :-)

2019-03-26 18:42 UTC, rssk commented on packages/coinstac-ui/app/main/index.js
> +      .catch((err) => { console.log(`Pipeline could not be stopped because of the following error: ${err}`)});
this should probably be logged using the winston instance and then sent to the UI toast handler

2019-06-20 19:59 UTC, rssk commented
Thanks for cleaning this up, one more quick task:

Can you add a stop button to the home page where the pipeline running widget is?

2019-06-21 16:45 UTC, rochaeb commented
> Thanks for cleaning this up, one more quick task:
> 
> Can you add a stop button to the home page where the pipeline running widget is?

done

2019-07-10 05:36 UTC, merged