Fix/364 unique pipeline consortium
MRN-Code/coinstac pull request #812
Opened 2020-02-03 19:24 UTC by kalitopix

# Problem
referenced issue(s):

# Solution

# Testing

closes #364

2020-02-12 00:40 UTC, rssk requested changes

2020-02-12 00:40 UTC, rssk commented on packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx
> +      console.log(graphQLErrors);
this log intended?

2020-02-12 00:41 UTC, kalitopix commented on packages/coinstac-ui/app/render/components/pipelines/pipeline.jsx
> +      console.log(graphQLErrors);
yes. want to remove?

2020-02-19 04:15 UTC, rssk approved these changes

2020-02-19 04:15 UTC, merged