Feature/864 docker manager test
MRN-Code/coinstac pull request #873
Opened 2020-04-30 12:06 UTC by kalitopix

# Problem
referenced issue(s):

# Solution

# Testing

2020-08-19 23:09 UTC, rssk requested changes
Good effort on coverage! but tests need some veracity checking addressed

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
Here as well as the other service, what is testing the veracity?

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +test.serial.before('startService2', async (t) => {
Unsure on serial usage

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
Same as the other service, what is this checking?

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
Again here, what is this checking? Having multiple clients is good to hit come code conditions on how `startService` gives you a service function, but why 3+ different tests for it?

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
Same issues here

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
This looks like it should be actually interaction with the service, but I see no verification of that

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +test.serial.before('stopService2', async (t) => {
same issues as previous

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +test.serial.before('stopAllServices', async (t) => {
Same as well

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +        .on('close', () => resolve())
What are these files for?

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/test/index.test.js
> +const httpServer = require('../../coinstac-images/coinstac-base/server-http');
I think this is a good way to include the files, but why have the mock servers too?

2020-08-19 23:09 UTC, rssk commented on packages/coinstac-docker-manager/package.json
> +    "unzipper": "^0.10.3",
Some of these are dev dependencies

2020-08-26 19:40 UTC, kalitopix commented on packages/coinstac-docker-manager/test/index.test.js
> +test.serial.before('startService6', async (t) => {
docker.createContainer is stubbed. If I don't use serial for this, it raises error.

`docker.createContainer is already stubbed.`

I have a lot of problems using Ava especially using same stubbed mock function several times as Ava runs tests asynchronously.

That's why I used serial a lot in these tests.

2020-08-26 19:41 UTC, kalitopix commented on packages/coinstac-docker-manager/test/index.test.js
> +  t.pass();
What do I have to compare here?

I used two services so that it can cover findAPortNotInUse function

2020-11-30 17:57 UTC, rssk approved these changes

2020-11-30 17:57 UTC, merged