Feature/892 coinstac api server test
MRN-Code/coinstac pull request #895
Opened 2020-05-28 14:43 UTC by kalitopix

# Problem
referenced issue(s):

# Solution

# Testing

closes #892

2020-07-15 15:53 UTC, rochaeb approved these changes

2020-08-20 06:25 UTC, rssk commented
Needs some merge conf fixes, note the newer test-setup

2020-09-08 18:06 UTC, rssk requested changes
re: merge conf

2020-10-14 20:55 UTC, rssk requested changes
Looking good, just a few comments and changes

2020-10-14 20:55 UTC, rssk commented on packages/coinstac-api-server/tests/resolvers.test.js
> +  t.true(res.called);
this is just saying this callback was called right? Could it have been called with an error? Why not just check if the error obj is false?

2020-10-14 20:55 UTC, rssk commented on packages/coinstac-api-server/tests/resolvers.test.js
> +});
nice hitting all the different states here 👍

2020-10-14 20:55 UTC, rssk commented on packages/coinstac-api-server/tests/resolvers.test.js
> +  await Mutation.updatePassword(auth, args);
should there be a test after this? Why not check if the password was updated via validate?

2020-10-14 20:55 UTC, rssk commented on packages/coinstac-api-server/tests/resolvers.test.js
> +// });
?

2020-11-11 23:50 UTC, rssk approved these changes

2020-11-11 23:50 UTC, merged